name: Frontend UI Tests

on: push

jobs:
  interaction-and-accessiblity:
    name: Interaction and Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and Angular CLI
        run: |
          npm install -g @angular/cli
          node -v
          npm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install

      - name: Serve Storybook
        run: |
          pnpm --filter @angular-commerce/shop storybook &
          until curl -s http://127.0.0.1:6006; do sleep 40; done
          pnpm --filter @angular-commerce/shop test-storybook