name: Frontend UI Tests

on: push

jobs:
  interaction-and-accessiblity:
    name: Interaction and Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and Angular CLI
        run: |
          npm install -g @angular/cli
          node -v
          npm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm --filter @angular-commerce/shop build-storybook

      - name: Serve Storybook
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && pnpm --filter @angular-commerce/shop test-storybook"